# Docker file for creating a container for RV tutorial 2020
# This docker file only handles Analysis Environment Demonstration

# Date of creation - 18.09.2020
# Maintainer -  omjaved

# OS package, without tag means we will always take the latest os image
FROM python:2.7

# Install dependencies
RUN apt-get update && apt-get install -y \
curl python-pip

# Installing and setting up virtual environment
RUN pip install virtualenv
RUN virtualenv venv --python=python2.7


# Current working directory to store repositories
WORKDIR tutorial/

# Source virtual directory
CMD source venv/bin/activate

# Clone verdict server
#RUN git clone https://github.com/pyvypr/VyPRServer.git
RUN git clone --single-branch --branch sync https://github.com/JesperStromblad/VyPRServer.git

# Cloning specific commit
#WORKDIR VyPRServer/
#RUN git checkout 6a12c9c3710cab2ff4832dd9d85d723f8b1e25a4

WORKDIR /tutorial/VyPRServer/

RUN pip install -r requirements.txt

#RUN git clone https://github.com/pyvypr/VyPR.git

#WORKDIR VyPR/

#RUN git checkout 4f6461adfe14ca5ffcebcf5237122c781ed067e1

RUN git clone --single-branch --branch sync https://github.com/JesperStromblad/VyPR.git

WORKDIR /tutorial/VyPRServer/

RUN curl -L http://cern.ch/vypr/data/verdicts-metadata-check-analysis.db -O

RUN mkdir monitored-service
RUN mkdir monitored-service/app

RUN curl -L http://cern.ch/vypr/data/uploader/app/metadata_handler.py.inst -o monitored-service/app/metadata_handler.py.inst
RUN curl -L http://cern.ch/vypr/data/uploader/app/routes.py.inst -o monitored-service/app/routes.py.inst

CMD python run_service.py --port 9002 --db verdicts-metadata-check-analysis.db --path monitored-service/





